# docker-compose.yml
version: '3.1'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=cofound
      - DATABASE_PASSWORD=cofound
      - DATABASE_NAME=cofound
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASSWORD=
      - PORT=3000
    depends_on:
      - db
      - elasticsearch
      - mailhog
    networks:
      - cofound-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cofound
      POSTGRES_USER: cofound
      POSTGRES_PASSWORD: cofound
    ports:
      - "5432:5432"
    networks:
      - cofound-network
    volumes:
      - ./dump/dump_11_06_2024.sql:/docker-entrypoint-initdb.d/dump.sql:ro
      - db_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - cofound-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - cofound-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - cofound-network

volumes:
  db_data:

networks:
  cofound-network:
    driver: bridge